package com.shopwizard.order.model;

import lombok.Data;

@Data
public class Order {
    private Integer orderNo;
    private Integer custId;
    private String loginId;
    private String recomId;
    private String orderName;
    private String orderCode;
    private String orderEmail;
    private String orderPhoneNo;
    private String orderMobileNo;
    private String orderZipcode;
    private String orderAddr1;
    private String orderAddr2;
    private String recverName;
    private String recverPhoneNo;
    private String recverMobileNo;
    private String recverZipcode;
    private String recverAddr1;
    private String recverAddr2;
    private String moneyUnit;
    private String deliMemo;
    private String orderMemo;
    private String deliHopeDate;
    private String orderState;
    private String orderReciptDate;
    private String orderCancelDate;
    private String payCmpletDate;
    private String shipDirectDate;
    private String shipCheckDate;
    private String shipCmpletDate;
    private String deliCmpletDate;
    private String refundReciptDate;
    private String refundRqstDate;
    private String refundCmpletDate;
    private String areaCode;
    private String chnlCode;
    private String remark;
    private Integer state;
    private String registDate;
    private String registId;
    private String registName;
    private String changeDate;
    private String changeId;
    private String changeName;
    // join fields
    private String chnlName;
    private String chnlUrl;
    private String chnlChrgName;
    private Integer orderAmt;
    private String prodName;
    private Integer prodCount;
    private Integer prodQty;
    private Integer readyCount;
    private Integer rejectCount;
    private Integer approvCount;
    private Integer deliCount;
    private Integer completeCount;
    private Integer cancelCount;
    private String payType;
    private String payTypeName;
    private String cardComp;
    private String reciptBank;
    private String approvNo;
    private String reciptName;
    private Integer payFee;
    private OrderPay orderPay;
}
