package com.shopwizard.adjust.model;

import lombok.Data;

@Data
public class AdjustDetail {
    private Integer adjustDetailNo;
    private Integer adjustNo;
    private Integer saleAdjustNo;
    private Integer orderNo;
    private Integer orderProdNo;
    private Integer orderChangeNo;
    private Integer custId;
    private String custLoginId;
    private String custName;
    private String supplyCode;
    private String supplyName;
    private String shopCode;
    private String shopName;
    private String deptName;
    private Integer bundleYn;
    private String cateCode;
    private String storeCode;
    private String prodCode;
    private String shopProdCode;
    private String itemCode;
    private String prodName;
    private String prodImg;
    private String itemName;
    private Integer prodQty;
    private Integer listPrice;
    private Integer prevPrice;
    private Integer salePrice;
    private Integer saleDiscntAmt;
    private Integer custCpnDiscntAmt;
    private Integer prodCpnDiscntAmt;
    private Integer pointUseAmt;
    private Integer supplyPrice;
    private Integer discntSupplyPrice;
    private Integer buyPrice;
    private Integer nvPrice;
    private Integer pvPrice;
    private Integer pointSaveAmt;
    private Integer vatRate;
    private Integer vatAmt;
    private Integer custChrgDeliFee;
    private Integer reciptAmt;
    private Integer giftRefundAmt;
    private Integer prodMargin;
    private Integer chnlMargin;
    private Integer netMargin;
    private Integer deliFeeId;
    private String deliFeeType;
    private Integer deliFeeAmt;
    private Integer deliCompCode;
    private String prevInvNo;
    private String invNo;
    private String payDate;
    private String payType;
    private String saleConfrmDate;
    private String saleAdjustCloseDate;
    private String buyAdjustCloseDate;
    private String orderReciptDate;
    private String cmpletDate;
    private String orderState;
    private String chnlCode;
    private Integer state;
    private String remark;
    private String registId;
    private String registName;
    private String registDate;
    private String changeId;
    private String changeName;
    private String changeDate;
}
