package com.shopwizard.catalog.model;

import lombok.Data;

@Data
public class Prod {
    private String prodCode;
    private String cateCode;
    private String cateName;
    private String shopCode;
    private String shopName;
    private String shopProdCode;
    private String impaProdCode;
    private String brandName;
    private String prodName;
    private String modelName;
    private String prodUnit;
    private String prodDsplName;
    private String invProdName;
    private String smsProdName;
    private String originName;
    private String makerName;
    private String keywrd;
    private Integer saleYn;
    private Integer supplyQty;
    private String attrName1; private String attrName2; private String attrName3; private String attrName4;
    private String attrValStr1; private String attrValStr2; private String attrValStr3; private String attrValStr4;
    private Integer listPrice;
    private Integer prevPrice;
    private Integer salePrice;
    private Integer discntPrice;
    private String discntStartDate;
    private String discntEndDate;
    private Integer supplyPrice;
    private Integer discntSupplyPrice;
    private Integer buyPrice;
    private Integer nvPrice;
    private Integer pvPrice;
    private Integer saveAmt;
    private Integer vatRate;
    private Integer vatAmt;
    private String prodDesc;
    private String imgUrl;
    private String imgUrl50; private String imgUrl80; private String imgUrl100;
    private String imgUrl160; private String imgUrl220; private String imgUrl280;
    private Integer deliFeeId;
    private String deliFeeName;
    private String deliMethod;
    private String deliFeeType;
    private Integer deliFeeAmt;
    private Integer deliMemoYn;
    private Integer leadTime;
    private String leadTimeReason;
    private String saleArea;
    private Integer deliCompId;
    private String bundleUnit;
    private Integer adultYn;
    private String sexualType;
    private String makeYear;
    private String kindType;
    private String seasonType;
    private String gradeType;
    private Integer asYn;
    private Integer cardDisableYn;
    private Integer cashDisableYn;
    private String sizeType;
    private String colorType;
    private String partDesc;
    private String approvId;
    private String approvName;
    private String approvDate;
    private String memo01;
    private String cateCode1; private String cateName1;
    private String remark;
    private Integer state;
    private String registDate; private String registId; private String registName;
    private String changeDate; private String changeId; private String changeName;
}
